package com.ssm.dao;

import com.ssm.entity.UserD;
import com.ssm.entity.UserDExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserDMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_d
     *
     * @mbggenerated
     */
    int countByExample(UserDExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_d
     *
     * @mbggenerated
     */
    int deleteByExample(UserDExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_d
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_d
     *
     * @mbggenerated
     */
    int insert(UserD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_d
     *
     * @mbggenerated
     */
    int insertSelective(UserD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_d
     *
     * @mbggenerated
     */
    List<UserD> selectByExample(UserDExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_d
     *
     * @mbggenerated
     */
    UserD selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_d
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserD record, @Param("example") UserDExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_d
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserD record, @Param("example") UserDExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_d
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_d
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserD record);
}